// _test/file_test/my_client/src/App.vue
<template>
  <div class="App">
    <h4>小文件上传</h4>
    <input type='file' @change="getFile"/>
    <button @click="toUploader">上传</button>
  </div>
</template>

<script>

import axios from 'axios'

export default {
  name: 'Home',
  data: function () {
    return {
      file: null,
    }
  },
  methods: {
    toUploader() {
      const {file} = this
      let url = '/api/hello'
      // const config = {
      //   headers: {'Content-Type': 'multipart/form-data;boundary=' + new Date().getTime()}
      // }
      const config = {}
      const formData = new FormData()
      formData.append('fileUpload', file, file.name)
      axios.post(url, formData, config).then(() => {
        console.log('上传文件成功')
      })
    },
    getFile(e) {
      this.file = e.target.files[0]
      console.log(this.file)
    }
  }
}
</script>

<style lang="scss">
</style>

// _test/file_test/my_client_react/src/App.js
import React, {Component} from 'react'

class App extends Component {

    state = {
        aFile: ''
    }

    fileUpload = e => {
        console.log('print')
        console.log(e.target.files[0])
    }

    render() {
        const {fileUpload} = this
        return (
            <div className="App">
                <h4>小文件上传</h4>
                <input type='file' onChange={fileUpload}/>
                <button onClick={fileUpload}>上传</button>
            </div>
        )
    }
}


export default App
